apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose --file ./docker-swarm/compose.yml convert
    kompose.version: 1.36.0 (ae2a39403)
  labels:
    io.kompose.service: result
  name: result
spec:
  type: NodePort
  ports:
    - name: "8081"
      port: 8081
      targetPort: 8080
      nodePort: 30081
  selector:
    io.kompose.service: result
