apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose --file ./docker-swarm/compose.yml convert
    kompose.version: 1.36.0 (ae2a39403)
  labels:
    io.kompose.service: result
  name: result
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: result
  template:
    metadata:
      annotations:
        kompose.cmd: kompose --file ./docker-swarm/compose.yml convert
        kompose.version: 1.36.0 (ae2a39403)
      labels:
        io.kompose.service: result
    spec:
      containers:
        - image: 0xkatana/result:latest
          name: result
          ports:
            - containerPort: 8080
              protocol: TCP
      restartPolicy: Always
