apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose --file ./docker-swarm/compose.yml convert
    kompose.version: 1.36.0 (ae2a39403)
  labels:
    io.kompose.service: vote
  name: vote
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: vote
  template:
    metadata:
      annotations:
        kompose.cmd: kompose --file ./docker-swarm/compose.yml convert
        kompose.version: 1.36.0 (ae2a39403)
      labels:
        io.kompose.service: vote
    spec:
      containers:
        - image: 0xkatana/vote:latest
          name: vote
          ports:
            - containerPort: 80
              protocol: TCP
      restartPolicy: Always
