apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose --file ./docker-swarm/compose.yml convert
    kompose.version: 1.36.0 (ae2a39403)
  labels:
    io.kompose.service: vote
  name: vote
spec:
  ports:
    - name: "8080"
      port: 8080
      targetPort: 80
  selector:
    io.kompose.service: vote
