apiVersion: v1
kind: Pod
metadata:
  name: vote-pod
  labels:
    app: vote-app
    name:  vote-pod
spec:
  containers: 
  - name: vote
    image:  kodekloud/examplevotingapp_vote:v1
    ports:
    - containerPort: 80