# service is like a dns / proxy in kubernetes
# used for mapping a ip to a hostname or a port to an external port 
# and it has 3 main types LoadBalancer | ClusterIP | NodePort
# by defualt is it a Clusterip 
# we specify nodeport so it becamse acessible from ourtise of the node external 

kind:  Service
apiVersion: v1
metadata:
  name:  vote-service
  labels:
    app: vote-app
    name:  vote-pod
spec:
  type: NodePort
  selector: 
    app: vote-app
    name:  db-pod
  ports:
  - port:  80
    targetPort: 80
    nodePort: 30004
