apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deploy
  labels: 
    name: db-deploy
    app: vote-app 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vote-app
      name: db-pod
  template:
    metadata:
      name: db
      labels:
        app: vote-app
        name: db-pod
    spec:
      containers: 
        - name: db
          image: postgres:15-alpine 
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD 
              value: postgres
          volumeMounts:
            - name: postgresdata
              mountPath: /var/lib/postgresql/data
      volumes: 
        - name: postgresdata
          emptyDir: {}
