apiVersion: apps/v1
kind: Deployment
metadata:
  name:  redis-deploy
  labels: 
    name: redis-deploy
    app: vote-app 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vote-app
      name:  redis-pod
  template:
    metadata:
      name: redis-pod
      labels:
        app: vote-app
        name:  redis-pod
    spec:
      containers: 
      - name: redis 
        image: redis:alpine
        ports:
        - containerPort: 6379