apiVersion: apps/v1
kind: Deployment
metadata:
  name:  result-deploy
  labels: 
    name: result-deploy
    app: vote-app 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vote-app
      name:  result-pod
  template:
    metadata:
      name: result-pod
      labels:
        app: vote-app
        name:  result-pod
    spec:
      containers: 
      - name: result-app 
        image:  kodekloud/examplevotingapp_result:v1
        ports:
        - containerPort: 80