# images are built from local files 
# file writteb by me but still missing some health checks 

services:
  db:
    image: postgres:15-alpine  
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
        - main-network

  redis:
    image: redis:alpine
    networks:
        - main-network

  vote:
    image: vote:vote_app
    build: 
      context: ./vote
      dockerfile: Dockerfile
      target: final
    ports:
      - "8080:80"  
    depends_on:
      - redis
    networks:
      - main-network

  result:
    image: result:result_app
    build: ./result
    ports:
      - "8081:8080"
    depends_on:
      - db
    networks:
      - main-network

  worker:  
    image: worker:worker_app
    build: ./worker
    depends_on:
      - db
      - redis
    networks:
      - main-network

networks:
  main-network:

volumes:
  postgres-data:

