name: deploy pipline worflow
on:
  push:
    branches:
      - main


jobs:
    run-deploy:
        if: contains(github.event.head_commit.message, 'deploy')
        runs-on: ubuntu-latest
        steps:
          - name: Docker stack deploy
            uses: cssnr/stack-deploy-action@v1
            with:
              name: vote-app
              file: deploy/docker-swarm/docker-stack.yml
              host: ${{ secrets.VPS_HOST }}
              user: ${{ secrets.VPS_USER }}
              ssh_key: ${{ secrets.VPS_SSH_KEY }}

          - name: Deploy Vote App Stack
            run: |
              docker stack deploy --compose-file deploy/docker-swarm/docker-stack.yml vote-app
        