name: Deploy Pipeline Workflow

on:
  push:
    branches:
      - main

    # This workflow will deploy the application to a VPS
jobs:
  run-deploy:
    if: contains(github.event.head_commit.message, 'deploy')
    runs-on: ubuntu-latest
    steps:
      - name: Docker stack deploy
        uses: cssnr/stack-deploy-action@v1
        with:
          name: vote-app
          file: deploy/docker-swarm/docker-stack.yml
          host: ${{ secrets.VPS_HOST }}
          user: ${{ secrets.VPS_USER }}
          ssh_key: ${{ secrets.VPS_SSH_KEY }}
