name: Publish Vote App Docker Images
# this workflow will build and push docker images 
# only if the commit message contains 'build'
on:
  push:
    branches:
      - main

jobs:
  main:
    if:  contains(github.event.head_commit.message, 'build')
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build and push Vote app
      uses: docker/build-push-action@v4
      with:
        context: ./vote
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/vote:latest

    - name: Build and push Result app
      uses: docker/build-push-action@v4
      with:
        context: ./result
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/result:latest

    - name: Build and push Worker app
      uses: docker/build-push-action@v4
      with:
        context: ./worker
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/worker:latest

    - name: Build and push Seed Data app
      uses: docker/build-push-action@v4
      with:
        context: ./seed-data
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/seed-data:latest